import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@mint-up/ui/globals.css";

import { AppHeader } from "./_shared/ui/layout/app-header";
import { BottomNav } from "./_shared/ui/layout/bottom-nav";
import { ConvexClientProvider } from "./_shared/ui/providers";
import { AuthKitProvider } from "./_shared/ui/providers/auth-kit-client.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthKitProvider>
          <ConvexClientProvider session={null}>
            <AppHeader />
            <div>{children}</div>
            <BottomNav />
          </ConvexClientProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
