import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@mint-up/ui/globals.css";
import "@farcaster/auth-kit/styles.css";

import { getSession } from "@/auth";

import { AppHeader } from "./_shared/ui/layout/app-header";
import { BottomNav } from "./_shared/ui/layout/bottom-nav";
import { ConvexClientProvider } from "./_shared/ui/providers";
import { AuthKitProvider } from "./_shared/ui/providers/auth-kit-client.provider";
import { ThemeProvider } from "./_shared/ui/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthKitProvider>
          <ConvexClientProvider session={session}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AppHeader />
              <div>{children}</div>
              <BottomNav />
            </ThemeProvider>
          </ConvexClientProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
