import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@mint-up/ui/globals.css";
import "@farcaster/auth-kit/styles.css";

import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import { getSession } from "@/auth";

import { MiniAppProvider } from "./_shared/lib/lemon";
import { getConfig } from "./_shared/lib/wagmi";
import { AppHeader } from "./_shared/ui/layout/app-header";
import { BottomNav } from "./_shared/ui/layout/bottom-nav";
import { ConvexClientProvider } from "./_shared/ui/providers";
import { AuthKitProvider } from "./_shared/ui/providers/auth-kit-client.provider";
import { WagmiClientProvider } from "./_shared/ui/providers/wagmi.provider";
import { ThemeProvider } from "./_shared/ui/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie"),
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthKitProvider>
          <ConvexClientProvider session={session}>
            <WagmiClientProvider initialState={initialState}>
              <MiniAppProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                >
                  <AppHeader />
                  <div>{children}</div>
                </ThemeProvider>
              </MiniAppProvider>
            </WagmiClientProvider>
          </ConvexClientProvider>
        </AuthKitProvider>
        <BottomNav />
      </body>
    </html>
  );
}
